# BUILD file for JSON schemas

filegroup(
    name = "schemas",
    srcs = [
        "grantha.schema.json",
        "grantha-envelope.schema.json",
        "grantha-part.schema.json",
    ],
    visibility = ["//visibility:public"],
)
