# BUILD file for upanishads/prasna
# Converts structured Markdown to JSON format

load("//tools/bazel:grantha_converter.bzl", "grantha_md2json_multipart")

grantha_md2json_multipart(
    name = "md2json",
    grantha_id = "prashna-upanishad",
    num_parts = 8,
)
